### ISSUE TITLE
Clase 3 POO Parte 8 Diseño de clases y Sobrecarga de Operadores

### ISSUE THREAD

**Issue by julietaagui** [CodeStrong2023/CodeMasters_3_sem#9]
- Crear la clase Producto: En carpeta Lección11
- Crear la clase Orden: Parte 1, 2 y 3
- Probar las clases Orden y Producto
- Sobrecarga de Operadores: Parte 1a hacerlo en carpeta Lección12
- Sobrecarga de Operadores: Parte 1b
- Sobrecarga de Operadores: Parte 2a
- Sobrecarga de Operadores: Parte 2b

**Comment by Romy-13** [comment]
Se cargan la Clase 3 POO diseño de clases y sobrecarga de operadores
